version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=ebike-shop
      - DB_USER=postgres
      - DB_PASSWORD=postgres
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=ebike-shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
